default_events:
  - pull_request

default_permissions:  
  metadata: read
  pull_requests: read
  commit_statuses: write


single_file_name: .github/wip.yml

name: WIP-go

description: \"DO NOT MERGE ❌\" - as a service!